SELECT * FROM mytable LIMIT 10;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) as revenue
from mytable
group by gender;

-- Q2. Which customer used a discount but still spent more than the average purchase amount? 

select customer_id , purchase_amount 
from mytable
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from mytable);

-- Q3. Which are the top 5 products with the highest average review rating

select item_purchased , round(AVG(review_rating),2) as Average_rating
from mytable
group by item_purchased
order by Average_rating desc
limit 5;

-- Q4. compare the average puchase amounts between standard and express shipping

select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount
from mytable
where shipping_type in ('Standard' , 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

select	subscription_status ,
count(customer_id),
round(avg(purchase_amount) ,2) as avg_spend ,
round(sum(purchase_amount),2) as total_revenue
from mytable
group by subscription_status
order by total_revenue , avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with dicount applied?
-- this measures out all puchases of this item , what fraction were discounted -> rate/percentage
select item_purchased ,
round(100* sum(case when discount_applied = 'Yes' Then 1 Else 0 END)/count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. segment customers into new , returning and loyal based on their 
-- number of previous purchases , and show the count of each segment

with customer_type as (
select customer_id , previous_purchases ,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from mytable)

select customer_segment , count(*) as 'Number of Customers'
from customer_type
group by customer_segment;

-- Q8. what are the top three most purchased products within each category?

with item_count as (
select category ,
item_purchased , 
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from mytable
group by category , item_purchased
)

SELECT item_rank , category , item_purchased , total_orders
from item_count
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous puchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from mytable
where previous_purchases >5
group by subscription_status;

-- Q10. what is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from mytable
group by age_group 
order by total_revenue desc;